swap_path:
    /fs03/pg32/zarul
preprocessing_path:
    /fs03/pg32/zarul/WES_analysis/results/preprocessing
out_path:
    single:
        /fs03/pg32/zarul/WES_analysis/results/single_calling
    joint:
        /fs03/pg32/zarul/WES_analysis/results/joint_calling
metadata:
    /projects/pg32/WES_analyses/input_folder/metadata.tsv
fastq_dir_path:
    /projects/pg32/WES_analyses/input_folder/datasets/raw_data
reference_genome_url:
    http://s3.amazonaws.com/nanopore-human-wgs/rna/referenceFastaFiles/dna/GRCh38_full_analysis_set_plus_decoy_hla.fa
gatk_bundle_url:
    ftp://gsapubftp-anonymous@ftp.broadinstitute.org/bundle/hg38
dbsnp_ref:
    /fs03/ie79/db/gatk_bundle_db/dbsnp_138.hg38.vcf.gz 
exon_bed:
    /projects/pg32/WES_analyses/input_folder/exome.bed
hapmap_resource:
    /fs03/ie79/db/gatk_bundle_db/hapmap_3.3.hg38.vcf.gz
mills_resource:
    /fs03/ie79/db/gatk_bundle_db/Mills_and_1000G_gold_standard.indels.hg38.vcf.gz
axiompoly_resource:
    /fs03/ie79/db/gatk_bundle_db/Axiom_Exome_Plus.genotypes.all_populations.poly.hg38.vcf.gz
dbsnp_resource:
    /fs03/ie79/db/gatk_bundle_db/Homo_sapiens_assembly38.dbsnp.vcf.gz
omni_resource:
    /fs03/ie79/db/gatk_bundle_db/1000G_omni2.5.hg38.vcf.gz
1000G_resource:
    /fs03/ie79/db/gatk_bundle_db/1000G_phase1.snps.high_confidence.hg38.vcf.gz
funcotator_resource:
    /fs03/pg32/zarul_db/funcotator_db/funcotator_dataSources.v1.6.20190124g
NA12878_validation_vcf:
    /projects/pg32/WES_analyses/input_folder/validation/HG001_GRCh38_1_22_v4.2.1_benchmark.vcf.gz
